version: '3.8'

services:
  db:
    image: vijayadk/libapp:dbimage
    container_name: db
    ports:
      - "3306:3306"
    

  auth_service:
    image: vijayadk/libapp:authimage
    container_name: auth_service
    ports:
      - "5001:5001"
    depends_on:
      - db
    

  book_service:
    image: vijayadk/libapp:bookimage
    container_name: book_service
    ports:
      - "5002:5002"
    
    

  borrow_service:
    image: vijayadk/libapp:borrowimage
    container_name: borrow_service
    ports:
      - "5003:5003"
    
  app_service:
    image: vijayadk/libapp:appimage
    container_name: app_service
    ports:
      - "5000:5000"
   
