---
version: '3'
services:
  db:
    image: vijayadk/pyapp:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
  auth_service:
    image: vijayadk/pyapp:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    depends_on:
      - db
  books_service:
    image: vijayadk/pyapp:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
  borrow_service:
    image: vijayadk/pyapp:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
  app_service:
    image: vijayadk/pyapp:appimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
